language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t luisfarfan19/docker-react -f Dockerfile.dev .

script:
  - docker run luisfarfan19/docker-react npm run test -- --coverage